"""Tests for the Ollama embedding provider."""

from __future__ import annotations

import httpx
import pytest

from philosophy_influence_explorer.embeddings.ollama import (
    OllamaEmbeddingProvider,
    OllamaEmbeddingProviderError,
)


def make_provider(dimensions: int = 3) -> OllamaEmbeddingProvider:
    """Create a small-dimension provider for isolated unit tests."""
    return OllamaEmbeddingProvider(
        base_url="http://ollama.test/",
        model="test-embedding-model",
        dimensions=dimensions,
        timeout_seconds=5.0,
    )


def make_response(payload: object, status_code: int = 200) -> httpx.Response:
    """Build an HTTP response for mocked Ollama calls."""
    request = httpx.Request("POST", "http://ollama.test/api/embed")
    return httpx.Response(
        status_code=status_code,
        json=payload,
        request=request,
    )


def test_embed_documents_posts_batch_and_returns_vectors(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Documents are sent as one batch and returned in response order."""
    captured: dict[str, object] = {}

    def fake_post(
        url: str,
        *,
        json: dict[str, object],
        timeout: float,
    ) -> httpx.Response:
        captured["url"] = url
        captured["json"] = json
        captured["timeout"] = timeout
        return make_response(
            {
                "embeddings": [
                    [0.1, 0.2, 0.3],
                    [0.4, 0.5, 0.6],
                ]
            }
        )

    monkeypatch.setattr(httpx, "post", fake_post)

    vectors = make_provider().embed_documents(["first", "second"])

    assert vectors == [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]
    assert captured == {
        "url": "http://ollama.test/api/embed",
        "json": {
            "model": "test-embedding-model",
            "input": ["first", "second"],
        },
        "timeout": 5.0,
    }


def test_embed_query_returns_single_vector(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A query returns the single embedding generated by Ollama."""
    monkeypatch.setattr(
        httpx,
        "post",
        lambda *args, **kwargs: make_response(
            {"embeddings": [[0.1, 0.2, 0.3]]}
        ),
    )

    assert make_provider().embed_query("What is becoming?") == [0.1, 0.2, 0.3]


def test_embed_documents_returns_empty_list_without_http_call(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """An empty document batch does not call Ollama."""
    def fail_if_called(*args: object, **kwargs: object) -> httpx.Response:
        raise AssertionError(
            "httpx.post must not be called for an empty batch")

    monkeypatch.setattr(httpx, "post", fail_if_called)

    assert make_provider().embed_documents([]) == []


@pytest.mark.parametrize(
    ("payload", "expected_message"),
    [
        ({}, "does not contain an 'embeddings' list"),
        ({"embeddings": [[0.1, 0.2]]}, "unexpected dimension"),
        (
            {"embeddings": [[0.1, "invalid", 0.3]]},
            "non-numeric value",
        ),
        (
            {"embeddings": [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]},
            "different number of embeddings",
        ),
    ],
)
def test_embed_documents_rejects_invalid_ollama_payload(
    monkeypatch: pytest.MonkeyPatch,
    payload: object,
    expected_message: str,
) -> None:
    """Malformed or inconsistent API responses fail with useful errors."""
    monkeypatch.setattr(
        httpx,
        "post",
        lambda *args, **kwargs: make_response(payload),
    )

    with pytest.raises(
        OllamaEmbeddingProviderError,
        match=expected_message,
    ):
        make_provider().embed_documents(["only input"])


def test_embed_documents_wraps_http_errors(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Transport failures become a provider-level error."""
    request = httpx.Request("POST", "http://ollama.test/api/embed")

    def raise_timeout(*args: object, **kwargs: object) -> httpx.Response:
        raise httpx.ReadTimeout("timed out", request=request)

    monkeypatch.setattr(httpx, "post", raise_timeout)

    with pytest.raises(
        OllamaEmbeddingProviderError,
        match="Could not generate embeddings with Ollama",
    ):
        make_provider().embed_documents(["text"])
